### ISSUE TITLE
Subscriber's stream is very fuzzy when publishing video from a video source

### ISSUE THREAD

**Issue by Lebron1992** [opentok/opentok-web-samples#103]
Hi, our company is using opentok for a while. We had tried to publish video from a video source. The workflow is good. But the stream subscribed by subscribers from the publisher video is very fuzzy, as shown in the following screenshot:

<img width="2480" alt="WechatIMG181" src="https://user-images.githubusercontent.com/13708531/67412363-b723a200-f5f1-11e9-9390-83a1f1a7c9e4.png">

The original video(a `1280x720` video) is on the bottom left, the subscriber stream is on the right which looks very fuzzy. I had tried to set the resolution to `1280x720`, but it didn't work:

```javascript
callProperties: {
    fitMode: 'contain',
    videoSource,
    audioSource,
    resolution: '1280x720'
},
```

I also went over the related docs, it says that resolution is ignored when publishing video from a video source. So any ideas to fix the issue? Thanks!

**Comment by warren32** [comment]
Did you ever figure out a solution to this?

**Comment by frankrod** [comment]
I had the same issue but it has nothing to do with the opentok publisher, the issue is when you do the `video.captureStream()`
the video by default uses the lowest resolution so when you do `captureStream()` your max resolution to use in the publisher would be the lowest of the video.
You could check this by logging your `stream.videoTracks()[0].getSettings()` you'll see the max resolution of the video.
What you can do is set the video player resolution to use the highest available by default so when you do `captureStream()` your `stream.videoTracks()[0]` would have the highest resolution and you can use same resolution in your publisher or downscale it.

**Comment by warren32** [comment]
I managed to get a somewhat workable solution to this.  The following solution will also work on ios. It needs more testing but the workflow is as follows:

1) Draw the video to a canvas using `requestAnimationFrame` and `context.drawImage()` as outlined here https://mux.com/blog/canvas-adding-filters-and-more-to-video-using-just-a-browser/.  Note that you can draw a canvas from a video element easily and adjust width, height and framerate using this technique.

2) Publish the canvas video stream using `canvas.captureStream(fps).getVideoTracks()[0]` like this:
```
OT.initPublisher(null, {
    videoSource: this.canvasEl
        .captureStream(30)
        .getVideoTracks()[0],
    insertDefaultUI: false,
    audioSource: false,
})
```
This is also shown here: https://github.com/opentok/opentok-web-samples/blob/master/Publish-Canvas/js/app.js. Note that `canvas.captureStream` is supported by all recent browsers (https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream)
