### ISSUE TITLE
Device selection sample

### ISSUE THREAD

**Issue by aullman** [opentok/opentok-web-samples#51]
👍 This if you would like to see a sample that shows you how to select devices. It would list available microphones/cameras and allow you to select one and publish. We already have https://github.com/opentok/opentok-hardware-setup.js but a sample here could be a bit simpler.

**Comment by nerdyglasses** [comment]
This would be really nice, because I'm stuck with this atm.

I've created a stream using OT.getUserMedia and I'm passing those tracks into a new OT.Publisher. The problem is when I unpublish this publisher destroy it and create a new one with different tracks then it doesn't publish anymore. I'm just getting black videos.

I'd like if I didn't need to unpublish the publisher at all but I couldn't find a way how to add and remove tracks from the publisher.

Here is what happens to me:

<img width="1503" alt="screenshot 2018-03-09 23 36 18" src="https://user-images.githubusercontent.com/449438/37233256-cf9d09c0-23f2-11e8-9646-a9da4ba2402e.png">

**Comment by aullman** [comment]
Yes, we are working on a feature to replace the tracks. The issue is we have been waiting for browsers to support this feature. Now Chrome supports it too and so we are looking into it. For now you do have to unpublish and publish a whole new Publisher unfortunately. 

That's a concern that you're getting black videos. Can you file your issue on Stackoverflow and we can find an answer for you there. https://stackoverflow.com/questions/tagged/tokbox+or+opentok

**Comment by aullman** [comment]
2.14 now has cycleVideo() https://tokbox.com/developer/sdks/js/reference/Publisher.html#cycleVideo

**Comment by nerdyglasses** [comment]
@aullman cool I'll put it on our roadmap!

**Comment by nerdyglasses** [comment]
@aullman we've just discovered that it's not possible to pass a new set of device ids. Unfortunately we cannot use this function.
