### ISSUE TITLE
Video not rendering on Android. Working on IOS!

### ISSUE THREAD

**Issue by MadhavChoudhary** [opentok/opentok-web-samples#88]
With one end running on Laptop (`macOS/Safari` in my case) and the other end running on (`IOS/Safari`) works like charm. But using (`Android/Chrome`) doesn't. I have tried possible options of trying different browsers and stuff. This doesn't seem to work on Android phones.  
Something like 'Hardware/Software required to process this video is not supported on your device'

**Comment by aullman** [comment]
These samples are set to use H.264 as the default codec so that they work in Safari. However some Android devices do not support H.264 properly because of the chipset. Most new Android devices should work but not all unfortunately. If working with Android is important to you then when you create your own project you should make them use VP8 instead of H.264 which is a setting for your project in the account portal.
